# Generated by Django 4.1.5 on 2023-04-12 11:26

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slogan', models.CharField(blank=True, max_length=150, null=True)),
                ('keywords', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
                'db_table': 'Kampanyalar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Kategori İsmi')),
                ('collection', models.CharField(blank=True, max_length=150, null=True, verbose_name='kolleksiyon')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('materialIcon', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTitle', models.CharField(max_length=50, verbose_name='Ürün İsmi')),
                ('productPrice', models.FloatField(verbose_name='Ürün Fiyatı')),
                ('productDescription', ckeditor.fields.RichTextField(verbose_name='Ürünün kısa Açıklaması')),
                ('productDetail', ckeditor.fields.RichTextField(verbose_name='Ürün Özellikleri')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ürün Görseli')),
                ('productShipping', models.BooleanField(default=False, verbose_name='Ücretsiz Kargo Mu')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('newSlug', autoslug.fields.AutoSlugField(blank=True, default='', editable=True, populate_from='productTitle', unique=True)),
                ('created_att', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('update_att', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('productCampaigns', models.ManyToManyField(blank=True, to='product.campaigns', verbose_name='Kampanya')),
                ('productCategorie', models.ManyToManyField(to='product.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'Renk'), ('size', 'Beden')], max_length=150, verbose_name='Variation Category')),
                ('variation_value', models.CharField(max_length=100, verbose_name='Variation Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'db_table': 'ProductVariations',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productTag',
            field=models.ManyToManyField(to='product.tag', verbose_name='Etiket'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Ürün-Resmi',
                'verbose_name_plural': 'Ürün-Resimleri',
                'db_table': 'Ürün-Resimleri',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=200)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'Bekliyor'), ('True', 'Onaylandı'), ('False', 'Reddedildi')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('update_att', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorum', to='product.product')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'db_table': 'Yorumlar',
            },
        ),
    ]
