# Generated by Django 4.1.5 on 2023-04-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='customer',
            new_name='user',
        ),
    ]
