# Generated by Django 4.1.5 on 2023-04-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('product_price', models.FloatField(verbose_name='Product Price')),
                ('ordered', models.BooleanField(default=False, verbose_name='Ordered')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('created_add', models.DateTimeField(auto_now_add=True, verbose_name='Created Add')),
            ],
            options={
                'verbose_name_plural': 'Sipariş Ürünleri',
                'db_table': 'Order_Items',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Order Number')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('address_title', models.CharField(max_length=50, verbose_name='Address Title')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('clear_address', models.CharField(max_length=500, verbose_name='Clear Address')),
                ('order_note', models.CharField(max_length=400, verbose_name='Order Note')),
                ('order_total', models.FloatField(verbose_name='Order Total')),
                ('tax', models.FloatField(verbose_name='Vergi')),
                ('status', models.CharField(choices=[('New', 'Yeni Sipariş'), ('Receipt', 'Receipt'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='New', max_length=20, verbose_name='Status')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP Address')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Is Ordered')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name_plural': 'Siparişler',
                'db_table': 'Orders',
            },
        ),
    ]
