# Generated by Django 4.1.5 on 2023-04-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='customer',
            new_name='user',
        ),
    ]
